version: '3.7'
services:
    db:
        container_name: todolist-mysql
        image: 'mysql:5.7'
        command: '--default-authentication-plugin=mysql_native_password --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci --init-connect=''SET NAMES UTF8MB4;'' --innodb-flush-log-at-trx-commit=0'
        restart: always
        ports:
            - '3306:3306'
        environment:
            - MYSQL_DATABASE=todolist_db_dev
            - MYSQL_USER=root
            - MYSQL_ROOT_PASSWORD=toDolist@!d
        networks:
            - backend
    api-service:
        image: todolist-api-image
        build:
            context: ./todolist-api
            dockerfile: Dockerfile
        ports:
            - '8080:8080'
        volumes:
            - /data/todolist-api-app
        restart: always
        depends_on:
            - db
        environment:
            - SPRING_DATASOURCE_URL=jdbc:mysql://db:3306/todolist_db_dev?useSSL=false
            - SPRING_DATASOURCE_USERNAME=root
            - SPRING_DATASOURCE_PASSWORD=toDolist@!d
        networks:
            - backend
            - frontend
    portal-service:
        container_name: todolist-portal-image
        build: ./todolist-portal
        volumes:
            - './todolist-portal:/usr/src/app'
        ports:
            - '4200:4200'
        command: "bash -c \"npm install && ng serve --host 0.0.0.0 --port 4200\"\n"
        restart: always
        depends_on:
            - api-service
        networks:
            - frontend
            
volumes:
    db-data:
networks:
    backend:
    frontend: